


version: '3.8'

# services:
#   jenkins:
#     image: jenkins/jenkins:lts
#     user: root
#     ports:
#       - "8080:8080"
#     volumes:
#       - jenkins_home:/var/jenkins_home
#       - /var/run/docker.sock:/var/run/docker.sock
#     networks:
#       - cicd

services:
  jenkins:
    image: jenkins-with-docker-cli
    user: root
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - cicd

    


  sonarqube:
    image: sonarqube:community
    ports:
      - "9000:9000"
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    networks:
      - cicd

  nexus:
    image: sonatype/nexus3
    ports:
      - "8082:8081"  # Access Nexus via http://localhost:8082
    volumes:
      - nexus-data:/nexus-data
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms512m -Xmx1024m
    networks:
      - cicd

volumes:
  jenkins_home:
  nexus-data:

networks:
  cicd:
